FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends ubuntu-desktop

#
#

RUN apt-get update && apt-get install -y --no-install-recommends \
	wget curl

# RUN apt-get install -y xz-utils

# RUN wget https://downloads.arduino.cc/arduino-1.8.19-linux64.tar.xz --directory-prefix=/usr/src/app

# RUN tar -xf /usr/src/app/arduino-1.8.19-linux64.tar.xz -C /usr/src/app

# RUN /usr/src/app/arduino-1.8.19/arduino-linux-setup.sh
# RUN /usr/src/app/arduino-1.8.19/install.sh

RUN mkdir -p /usr/src/app



ENV NPM_CONFIG_PREFIX=/home/arduino/.npm-global
ENV PATH="${PATH}:/home/arduino/.npm-global/bin"
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs

RUN apt-get install -y build-essential

ARG USER_UID
ARG USER_GID

RUN groupadd --gid $USER_GID arduino && useradd --uid $USER_UID --gid $USER_GID --groups dialout,sudo --create-home arduino
RUN echo "arduino:Mb921" | chpasswd

RUN wget -O /home/arduino/arduino-ide.AppImage https://downloads.arduino.cc/arduino-ide/arduino-ide_2.0.0-rc9.2_Linux_64bit.AppImage
RUN chmod +x /home/arduino/arduino-ide.AppImage

COPY ./arduino-ide-initial-settings.json /home/arduino/.arduinoIDE/settings.json
RUN chown -R arduino:arduino /home/arduino/.arduinoIDE

# https://github.com/Rahix/avr-hal
RUN apt-get update && apt-get install -y avr-libc gcc-avr pkg-config avrdude libudev-dev

RUN apt-get install -y sudo

USER arduino
WORKDIR /home/arduino

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
ENV PATH="/home/arduino/.cargo/bin:${PATH}"
# https://github.com/Rahix/avr-hal
RUN cargo +stable install ravedude
RUN cargo install cargo-generate

RUN ./arduino-ide.AppImage --appimage-extract

ENV USER=arduino
ENV RAVEDUDE_PORT=/dev/ttyACM0

CMD ["/home/arduino/squashfs-root/arduino-ide", "--no-sandbox"]
